// this file is automatically generated
#include <stdint.h>
#include <stddef.h>

#include "propag.h"

#include "conf_globparam.propag.h"
#include "conf_led.propag.h"
#include "conf_turnout.propag.h"
#include "conf_train.propag.h"
#include "conf_topology.propag.h"
#include "conf_canton.propag.h"
#include "conf_boards.propag.h"


void conf_propagate(int confnum, int fieldnum, int instnum, int32_t v)
{
    switch (confnum) {
    case conf_pnum_led:
        conf_led_propagate(instnum, fieldnum, v);
        break;
    case conf_pnum_turnout:
        conf_turnout_propagate(instnum, fieldnum, v);
        break;
    case conf_pnum_train:
        conf_train_propagate(instnum, fieldnum, v);
        break;
    case conf_pnum_canton:
        conf_canton_propagate(instnum, fieldnum, v);
        break;
    default: break;
    }

}

