// this file is automatically generated
#include <stdint.h>
#include <stddef.h>

#include "propag.h"



void conf_propagate(unsigned int confnum, unsigned int fieldnum, unsigned int instnum, int32_t v)
{
    switch (confnum) {
    default: break;
    }

}



int32_t conf_default_value(unsigned int confnum, unsigned int fieldnum, unsigned int board, unsigned int instnum)
{
    switch (confnum) {
    default: return 0;
    break;
    }

}



void *conf_local_ptr(unsigned int lconfnum)
{
    switch (lconfnum) {
       default: return NULL;
    }
    return NULL;
}




unsigned int conf_local_size(unsigned int lconfnum)
{
    switch (lconfnum) {
       default: return 0;
    }
    return 0;
}




int32_t conf_local_get(unsigned int lconfnum, unsigned int fieldnum, unsigned int instnum)
{
    switch (lconfnum) {
       default: return 0;
    }
    return 0;
}




void conf_local_set(unsigned int lconfnum, unsigned int fieldnum, unsigned int instnum, int32_t v)
{
    switch (lconfnum) {
       default: break;
    }
}


